import React, { memo } from 'react';
import PropTypes from 'prop-types';
import { Box, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Paper } from '@mui/material';
import MenuPopover from '../menu-popover/MenuPopover';
import FormLabel from '../DocumentForms/FormLabel';
import { fDateTime } from '../../utils/formatTime';

function ViewFormMachinePortalKeyHistory({ open, onClose, ListArr, ListTitle }) {
  return (
    <MenuPopover open={open} onClose={onClose} sx={{ p: 0 }}>
      <Box sx={{ py: 1, px: 1 }} alignContent="center" alignItems="center" >
        <FormLabel content={ListTitle} />
        <TableContainer component={Paper} >
          <Table size="small" aria-label="a dense table" >
            <TableHead>
              <TableRow>
                <TableCell align='left' >Version</TableCell>
                <TableCell align='left' >Generated By</TableCell>
                <TableCell align='left' >Date</TableCell>
                <TableCell align='left' >IP Address</TableCell>
                <TableCell align='left' >Portal Key</TableCell>
              </TableRow>
            </TableHead>
            <TableBody>
              {ListArr && ListArr.map((m, index) => (
                <TableRow key={m?._id} sx={{ '&:last-child td, &:last-child th': { border: 0 } }} >
                  <TableCell align='left'>{`v${ListArr.length - index}${index === 0 ? " (Active)":""}`}</TableCell>
                  <TableCell align='left'>{m?.createdBy?.name || ''}</TableCell>
                  <TableCell align='left'>{fDateTime(m?.createdAt) || ''}</TableCell>
                  <TableCell align='left'>{m?.createdIP || ''}</TableCell>
                  <TableCell align='left'>{m?.key || ''}</TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </TableContainer>
      </Box>
    </MenuPopover>
  );
}

export default memo(ViewFormMachinePortalKeyHistory);

ViewFormMachinePortalKeyHistory.propTypes = {
  open: PropTypes.object,
  onClose: PropTypes.func,
  ListArr: PropTypes.array,
  ListTitle: PropTypes.string,
};
