export const AddMachineSchema = Yup.object().shape({
    serialNo: Yup.string().max(100).required('Serial Number is required'),
    name: Yup.string().max(50),
    // parentMachine: Yup.string(),
    // parentSerialNo: Yup.string(),
    // supplier: Yup.string(),
    // machineModel: Yup.string(),
    // status: Yup.string(),
    workOrderRef: Yup.string().max(50),
    // customer:Yup.string(),
    // instalationSite: Yup.string(),
    // billingSite: Yup.string(),
    // accountManager: Yup.string(),
    // projectManager: Yup.string(),
    // supportManager: Yup.string(),
    customerTags: Yup.array(),
    description: Yup.string().max(1500),
    isDisabled : Yup.boolean(),
  });